export const BOT_NAMES = [
    "Dog", "Cat", "Unity", "Beanie", "Blob", "Guest", "Pro", "Noob", "Team?", 
    "W=Team", "Feed Me", "Jumbo", "Tiny", "Mars", "Earth", "Pluto", "NASA", 
    "SpaceX", "Tesla", "Doge", "Bitcoin", "Ethereum", "Moon", "Sun", "Star", 
    "Galaxy", "Comet", "Meteor", "Nebula", "Orbit", "Gravity", "Physics", 
    "Math", "Science", "Biology", "Cell", "Mitosis", "Meiosis", "Nucleus", 
    "Mitochondria", "Virus", "Bacteria", "Fungi", "Algae", "Prokaryote", 
    "Eukaryote", "Agar", "Gel", "Petri", "Dish", "Lab", "Test1", "Test2", 
    "Player", "User", "Admin", "Mod", "Dev", "Hacker", "Glitch", "Bug", 
    "Feature", "Code", "Script", "Java", "Python", "Rust", "Go", "C++", 
    "C#", "HTML", "CSS", "JS", "TS", "React", "Vue", "Angular", "Node", 
    "Deno", "Bun", "Vite", "Webpack", "Rollup", "Esbuild", "Babel", "SWC", 
    "Turbo", "Monorepo", "Git", "GitHub", "GitLab", "Bitbucket", "Jira", 
    "Trello", "Slack", "Discord", "Zoom", "Skype", "Teams", "Meet", "Chat", 
    "Voice", "Video", "Stream", "Twitch", "YouTube", "TikTok", "Insta", 
    "Facebook", "Twitter", "X", "Reddit", "LinkedIn", "Snapchat", "Pinterest", 
    "Tumblr", "Flickr", "Vimeo", "Dailymotion", "Netflix", "Hulu", "Disney", 
    "Prime", "HBO", "Apple", "Google", "Microsoft", "Amazon", "Meta", 
    "Nvidia", "AMD", "Intel", "Samsung", "Sony", "LG", "Panasonic", "Toshiba", 
    "Sharp", "Sanyo", "Hitachi", "Fujitsu", "NEC", "IBM", "Dell", "HP", 
    "Lenovo", "Asus", "Acer", "MSI", "Razer", "Logitech", "Corsair", 
    "SteelSeries", "HyperX", "Zowie", "BenQ", "ViewSonic", "AOC", "Philips", 
    "Canon", "Nikon", "Fuji", "Kodak", "Olympus", "Pentax", "Leica", 
    "Hasselblad", "PhaseOne", "Red", "Arri", "Blackmagic", "GoPro", "DJI", 
    "Drone", "Robot", "AI", "ML", "DL", "NN", "GPT", "LLM", "BERT", 
    "Transformer", "Attention", "Diffusion", "GAN", "VAE", "RL", "Agent", 
    "Bot", "NPC", "Mob", "Boss", "Level", "Stage", "World", "Zone", 
    "Area", "Region", "Map", "Chart", "Graph", "Plot", "Data", "Info", 
    "Knowledge", "Wisdom", "Truth", "Facts", "News", "Media", "Press", 
    "Report", "Paper", "Article", "Blog", "Post", "Tweet", "Status", 
    "Story", "Reel", "Short", "Clip", "Video", "Audio", "Music", "Song", 
    "Track", "Album", "Artist", "Band", "Group", "Singer", "Rapper", 
    "Producer", "DJ", "Composer", "Writer", "Author", "Poet", "Painter", 
    "Sculptor", "Actor", "Actress", "Director", "Star", "Celebrity", 
    "Fame", "Wealth", "Money", "Cash", "Gold", "Silver", "Bronze", 
    "Platinum", "Diamond", "Ruby", "Emerald", "Sapphire", "Pearl", "Opal", 
    "Topaz", "Jade", "Onyx", "Quartz", "Granite", "Marble", "Stone", 
    "Rock", "Sand", "Dirt", "Mud", "Clay", "Dust", "Ash", "Smoke", 
    "Fire", "Water", "Air", "Wind", "Earth", "Light", "Dark", "Shadow", 
    "Shade", "Color", "Hue", "Sat", "Val", "RGB", "CMYK", "HEX", 
    "HSL", "HSV", "LAB", "XYZ", "YUV", "YIQ", "Luma", "Chroma", 
    "Pixel", "Voxel", "Texel", "Vertex", "Edge", "Face", "Poly", 
    "Mesh", "Model", "Scene", "Camera", "Light", "Material", "Shader", 
    "Texture", "Sprite", "Image", "Bitmap", "Vector", "Curve", "Spline", 
    "NURBS", "Path", "Shape", "Form", "Space", "Time", "Dimension", 
    "Universe", "Cosmos", "Nature", "Life", "Death", "Spirit", "Soul", 
    "Mind", "Body", "Heart", "Brain", "Eye", "Ear", "Nose", "Mouth", 
    "Hand", "Foot", "Leg", "Arm", "Head", "Face", "Hair", "Skin", 
    "Bone", "Blood", "Cell", "Gene", "DNA", "RNA", "Protein", "Enzyme", 
    "Hormone", "Vitamin", "Mineral", "Nutrient", "Food", "Drink", "Meal", 
    "Dish", "Plate", "Bowl", "Cup", "Glass", "Bottle", "Can", "Box", 
    "Bag", "Sack", "Pack", "Cart", "Wagon", "Truck", "Car", "Bike", 
    "Bus", "Train", "Plane", "Ship", "Boat", "Yacht", "Sub", "Jet", 
    "Rocket", "UFO", "Alien", "Martian", "Venusian", "Jovian", "Saturnian", 
    "Uranian", "Neptunian", "Plutonian", "Solar", "Lunar", "Stellar", 
    "Galactic", "Universal", "Eternal", "Finite", "Infinite", "Zero", 
    "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", 
    "Nine", "Ten", "Hundred", "Thousand", "Million", "Billion", "Trillion", 
    "Quadrillion", "Quintillion", "Sextillion", "Septillion", "Octillion", 
    "Nonillion", "Decillion", "Googol", "Infinity", "Alpha", "Beta", 
    "Gamma", "Delta", "Epsilon", "Zeta", "Eta", "Theta", "Iota", 
    "Kappa", "Lambda", "Mu", "Nu", "Xi", "Omicron", "Pi", "Rho", 
    "Sigma", "Tau", "Upsilon", "Phi", "Chi", "Psi", "Omega", "Aleph", 
    "Beth", "Gimel", "Dalet", "He", "Vau", "Zayin", "Cheth", "Teth", 
    "Yod", "Kaph", "Lamed", "Mem", "Nun", "Samekh", "Ayin", "Pe", 
    "Tzaddi", "Qoph", "Resh", "Shin", "Tau", "Japan", "USA", "UK", 
    "China", "Russia", "Germany", "France", "Italy", "Spain", "Brazil", 
    "India", "Canada", "Australia", "Korea", "Mexico", "Turkey", 
    "Indonesia", "Saudi", "Iran", "Poland", "Sweden", "Norway", "Finland", 
    "Denmark", "Holland", "Belgium", "Swiss", "Austria", "Greece", 
    "Egypt", "SouthAfrica", "Nigeria", "Kenya", "Argentina", "Chile", 
    "Peru", "Colombia", "Venezuela", "Vietnam", "Thailand", "Malaysia", 
    "Singapore", "Philippines", "Taiwan", "HongKong", "Macau", "Tibet", 
    "Nepal", "Bhutan", "Pakistan", "Afghan", "Iraq", "Syria", "Lebanon", 
    "Jordan", "Israel", "Palestine", "Kuwait", "Qatar", "UAE", "Oman", 
    "Yemen", "Sudan", "Libya", "Tunisia", "Algeria", "Morocco", "Cuba", 
    "Haiti", "Jamaica", "Bahamas", "Bermuda", "Panama", "CostaRica", 
    "Nicaragua", "Honduras", "Guatemala", "Belize", "Salvador", "Ecuador", 
    "Bolivia", "Paraguay", "Uruguay", "Guyana", "Surilesotho", "Swazi", 
    "Namibia", "Botswana", "Zimbabwe", "Zambia", "Angola", "Congo", 
    "Gabon", "Cameroon", "Chad", "Niger", "Mali", "Senegal", "Gambia", 
    "Guinea", "Sierra", "Liberia", "Ivory", "Ghana", "Togo", "Benin", 
    "Burkina", "Somalia", "Ethiopia", "Eritrea", "Djibouti", "Uganda", 
    "Rwanda", "Burundi", "Tanzania", "Malawi", "Mozambique", "Madagascar", 
    "Mauritius", "Seychelles", "Comoros", "Maldives", "Lanka"
];
